language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - BOARD=esp01 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266 EXTRAS="--project-option=lib_ignore=WiFi101"
    - BOARD=nodemcuv2 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266 EXTRAS="--project-option=lib_ignore=WiFi101"
    - BOARD=uno PLATFORMIO_CI_SRC=examples/SimpleLogging
    - BOARD=megaatmega1280 PLATFORMIO_CI_SRC=examples/SimpleLogging
    - BOARD=yun PLATFORMIO_CI_SRC=examples/SimpleLoggingYun
    - BOARD=zero PLATFORMIO_CI_SRC=examples/SimpleLoggingWiFi EXTRAS="--project-option=lib_ignore=WiFi101 --project-option=lib_deps=WiFi"
    - BOARD=mkr1000USB PLATFORMIO_CI_SRC=examples/SimpleLoggingWiFi101_MKR1000

install:
    - pip install -U platformio
    - rm -rf ./linux

    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/299/WiFi101

    - platformio lib -g install 299

script:
    - platformio ci -v --lib="." --board=$BOARD $EXTRAS